<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VoidNote.Application\VoidNote.Application.csproj" />
    <ProjectReference Include="..\VoidNote.Audio\VoidNote.Audio.csproj" />
    <ProjectReference Include="..\VoidNote.Domain\VoidNote.Domain.csproj" />
    <ProjectReference Include="..\VoidNote.Infrastructure\VoidNote.Infrastructure.csproj" />
    <ProjectReference Include="..\VoidNote.GameBridge\VoidNote.GameBridge.csproj" />
    <ProjectReference Include="..\VoidNote.Midi\VoidNote.Midi.csproj" />
    <ProjectReference Include="..\VoidNote.Shawzin\VoidNote.Shawzin.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>
</Project>
