using VoidNote.Domain.Audio;

namespace VoidNote.Domain.Music;

/// <summary>Identifies how a normalized musical event was created.</summary>
public enum MusicalEventSource
{
    /// <summary>The event came from a MIDI import.</summary>
    ImportedMidi,
    /// <summary>The event came from audio transcription.</summary>
    AudioTranscription,
    /// <summary>The event was entered manually.</summary>
    Manual,
    /// <summary>The event came from a Shawzin recording.</summary>
    ShawzinRecording,
    /// <summary>The event was generated by a transformation.</summary>
    Generated,
}

/// <summary>Represents a normalized note event shared by all music modules.</summary>
public sealed record MusicalEvent
{
    /// <summary>Creates a validated musical event.</summary>
    public MusicalEvent(
        Guid id,
        MusicalTime startTime,
        MusicalTime duration,
        int pitch,
        int velocity,
        MusicalEventSource source,
        decimal confidence,
        AudioNoteProvenance? audioProvenance = null)
    {
        if (id == Guid.Empty) throw new ArgumentException("An event ID cannot be empty.", nameof(id));
        if (pitch is < 0 or > 127) throw new ArgumentOutOfRangeException(nameof(pitch));
        if (velocity is < 0 or > 127) throw new ArgumentOutOfRangeException(nameof(velocity));
        if (confidence is < 0m or > 1m) throw new ArgumentOutOfRangeException(nameof(confidence));

        Id = id;
        StartTime = startTime;
        Duration = duration;
        Pitch = pitch;
        Velocity = velocity;
        Source = source;
        Confidence = confidence;
        AudioProvenance = audioProvenance;
    }

    /// <summary>Gets the stable event identifier.</summary>
    public Guid Id { get; }
    /// <summary>Gets the event position on the master timeline.</summary>
    public MusicalTime StartTime { get; }
    /// <summary>Gets the event duration in timeline ticks.</summary>
    public MusicalTime Duration { get; }
    /// <summary>Gets the normalized MIDI-style pitch from 0 through 127.</summary>
    public int Pitch { get; }
    /// <summary>Gets the normalized velocity from 0 through 127.</summary>
    public int Velocity { get; }
    /// <summary>Gets the event origin.</summary>
    public MusicalEventSource Source { get; }
    /// <summary>Gets the source confidence from zero through one.</summary>
    public decimal Confidence { get; }
    /// <summary>Gets durable transcription origin and raw timing, when this note came from audio.</summary>
    public AudioNoteProvenance? AudioProvenance { get; }
}
